name: Trigger workflow

on:
  push:
    branches:
      - develop
    paths:
      - 'fastlane/release-notes.txt'
  pull_request:
    types:
      - closed

# 使用并发
concurrency:
  # 组名
  group: ${{ github.workflow }}-${{ github.ref }}
  # 是否取消当前正在进行的进程
  cancel-in-progress: true

jobs:
  DownloadFile:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: self-hosted
    outputs:
      REPOSITORY_NAME: ${{ steps.setEnv.outputs.REPOSITORY_NAME }}
      GROUP_NAME: ${{ steps.setEnv.outputs.GROUP_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set ENV
        id: setEnv
        run: |
          # 获取仓库名称
          repository_name="${{ github.repository }}"
          repository_name="${repository_name#*/}"  # 删除第一个斜杠及之前的内容
          echo "REPOSITORY_NAME=$repository_name" >> "$GITHUB_ENV"
          echo "REPOSITORY_NAME=$repository_name" >> "$GITHUB_OUTPUT"

          group_name=""
          workspace_path="${{ github.workspace }}"
          runner_name="actions-runner-2"

          if [[ $workspace_path == *$runner_name* ]]; then
            group_name="Backup-Group"
            echo "my_string 包含子字符串 '$runner_name'"
          else
            group_name="Default"
            echo "my_string 不包含子字符串 '$runner_name'"
          fi
          echo "$group_name"
          echo "GROUP_NAME=$group_name" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: retro-labs/tools-scripting
          token: ${{ secrets.GH_PAT }}
          ref: main
          path: envFiles

      - name: remove .git Documents & rsync files
        run: |
          BACKUP_DIR_PATH=${HOME}"/Documents/Backup/"
          rm -rf ${BACKUP_DIR_PATH}/envFiles
          rm -rf ./envFiles/.git
          cp -rf ./envFiles ${BACKUP_DIR_PATH}
          rm -rf ./envFiles/.github
          rsync -av --ignore-existing envFiles/ ./
          cp ./fastlane/${{ env.REPOSITORY_NAME }}/* ./fastlane/ && rm -rf ./fastlane/${{ env.REPOSITORY_NAME }}
          rm -rf ./envFiles

  ChooseWorkflow:
    needs: DownloadFile
    uses: retro-labs/tools-scripting/.github/workflows/ChooseWorkflow.yml@main
    with:
      ProjectName: "${{ needs.DownloadFile.outputs.REPOSITORY_NAME }}"
      BranchName: "${{ github.ref_name }}"
      RunnerName: "${{ needs.DownloadFile.outputs.GROUP_NAME }}"
    secrets: inherit
